apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter 
  labels:
    app.kubernetes.io/name: jupyter  
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyter 
    spec:
      containers:
      - name: jupyter 
        imagePullPolicy: Always 
        image: "dodasts/spark:v0.0.11-spark"
        command:
          - jupyter-notebook
          - --allow-root
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter 
  
  replicas: 1
  strategy:
    type: Recreate