apiVersion: v1 
kind: Service 
metadata:
  name: jupyter 
spec:
  type: NodePort 
  ports:
    - port: 8888
      nodePort: 31888 
      protocol: TCP
      name: jupyter
  selector:
    app.kubernetes.io/name: jupyter