# FROM dodasts/cygno-lab:<latest release> -> for example:
FROM dodasts/cygno-lab:v1.0.13-cygno

RUN pip3 install --no-cache-dir -U git+https://github.com/CYGNUS-RD/cygno.git
RUN pip3 install 'https://github.com/CYGNUS-RD/middleware/blob/master/midas/midaslib.tar.gz?raw=true'
RUN pip3 install tensorflow
# RUN pip3 install keras
RUN pip3 install opencv-python
