---
  # Source: spark/templates/spark-master-deployment.yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: default-pyspark
    namespace: default
  subjects:
  - kind: User
    name: system:serviceaccount:default:default
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: edit
    apiGroup: rbac.authorization.k8s.io
  ---
  # Source: spark/templates/spark-master-deployment.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: hub-webui
    labels:
      component: "hub"
  spec:
    ports:
      - port: 8888
        targetPort: 8888
        nodePort: 30888
    selector:
      component: "hub"
    type: NodePort
  ---
  # Source: spark/templates/spark-master-deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hub
    labels:
      component: "hub"
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        component: "hub"
    template:
      metadata:
        labels:
          component: "hub"
      spec:
        containers:
          - name: jupyter
            imagePullPolicy: Always
            command: ["jupyterhub", "--port", "8888", "--config", "./.init/jupyterhub_config.py"]
            env:
              - name: OAUTH_CALLBACK_URL
                value: "http://90.147.174.54:30888/hub/oauth_callback"
              - name: OAUTH_ENDPOINT
                value: "https://iam.cloud.infn.it"
              - name: S3_ENABLED
                value: "false"
            image: "dciangot/hub:testnew14"
            ports:
            - containerPort: 8888
            volumeMounts:
            - mountPath: /home/jovyan/work
              name: jupyter-data
        volumes:
        - name: jupyter-data
          hostPath:
            path: /tmp