---
# Source: spark/templates/spark-master-deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-pyspark
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
# Source: spark/templates/spark-master-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: spark2-master
  labels:
    heritage: "Helm"
    release: "spark2"
    chart: "spark-1.0.3"
    component: "spark2-spark-master"
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: "spark2-spark-master"
---
# Source: spark/templates/spark-master-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: spark2-webui
  labels:
    heritage: "Helm"
    release: "spark2"
    chart: "spark-1.0.3"
    component: "spark2-spark-master"
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    component: "spark2-spark-master"
  type: LoadBalancer
---
# Source: spark/templates/spark-master-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark2-master
  labels:
    heritage: "Helm"
    release: "spark2"
    chart: "spark-1.0.3"
    component: "spark2-spark-master"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "spark2-spark-master"
  template:
    metadata:
      labels:
        heritage: "Helm"
        release: "spark2"
        chart: "spark-1.0.3"
        component: "spark2-spark-master"
    spec:
      containers:
        - name: master
          image: "dciangot/spark-py:v2.4.5"
          command: ["/bin/sh","-c"]
          args: ["echo $(hostname -i) spark2-master >> /etc/hosts; /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h localhost -p 7077"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
          env:
          - name: SPARK_DAEMON_MEMORY
            value: "1g"
          - name: SPARK_MASTER_HOST
            value: spark2-master
          - name: SPARK_MASTER_PORT
            value: "7077"
          - name: SPARK_MASTER_WEBUI_PORT
            value: "8080"
        - name: jupyter
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          #command: ["start.sh"]
          #args: ["/usr/local/spark/bin/pyspark"]
          env:
            - name: PYSPARK_PYTHON
              value: python3
            - name: PYSPARK_DRIVER_PYTHON
              value: jupyter
              #value: ipython
            - name: PYSPARK_DRIVER_PYTHON_OPTS
              value: "notebook --NotebookApp.token=testme --no-browser"
            - name: JUPYTER_TOKEN
              value: "testme"
          image: "dciangot/swan:v2.4.5-7"
          #image: "dciangot/pyspark-notebook:v2.4.5-12"
          #image: "dodasts/pyspark-notebook:v2.0.0-rc1"
          ports:
          - containerPort: 8888
          volumeMounts:
          - mountPath: /home/jovyan/work
            name: jupyter-data  
      volumes:
      - name: jupyter-data
        hostPath:
          path: /tmp
