name: dask build

on:
  push:
    tags: 
    - "*-fermi"

jobs:
  dask:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dodasts/jlab-htc-dask # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - 
        name: Build container image
        uses: docker/build-push-action@v2
        with: 
          context: ./docker/htcondor/fermi
          file: ./docker/htcondor/fermi/Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/386
          platforms: linux/amd64
          outputs: "type=registry,push=true"
          tags: |
              ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/execute-fermi:${{ env.RELEASE_VERSION }}
              ${{ steps.docker_meta.outputs.tags }}
