name: monitoring check

on:
  push:
    paths:
      - "!docker/**"
      - "docker/monitoring/**"
  pull_request:
    paths:
      - "!docker/**"
      - "docker/monitoring/**"

jobs:
  dockerlint-grafana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "docker/monitoring/grafana/Dockerfile"
          failure-threshold: error

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "docker/monitoring"
          severity: error
