name: single-node-jupyterhub check

on:
  push:
    paths:
      - "!docker/**"
      - "docker/single-node-jupyterhub/**"
  pull_request:
    paths:
      - "!docker/**"
      - "docker/single-node-jupyterhub/**"

jobs:
  dockerlint:
    strategy:
      matrix:
        dockerfile:
          - docker/single-node-jupyterhub/notebook/Dockerfile
          - docker/single-node-jupyterhub/lab/Dockerfile
          - docker/single-node-jupyterhub/lab/Dockerfile.cc7
          - docker/single-node-jupyterhub/lab/base-persistence/Dockerfile
          - docker/single-node-jupyterhub/jupyterlab-collaborative-proxy/Dockerfile
          - docker/single-node-jupyterhub/jupyterlab-collaborative/Dockerfile
          - docker/single-node-jupyterhub/jupyterhub/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ matrix.dockerfile }}
          failure-threshold: error

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "docker/single-node-jupyterhub"
          severity: error
